export default [
  {
    name: 'Monday',
    temp: 10,
    description: 'clear sky',
    huminidy: '45%',
    pressure: 1021,
    icon: 'cloud',
  },
  {
    name: 'Tuesday',
    temp: 20,
    description: 'clear sky',
    huminidy: '45%',
    pressure: 1021,
    icon: 'sun',
  },
  {
    name: 'Wednesday',
    temp: 8,
    description: 'clear sky',
    huminidy: '45%',
    pressure: 1021,
    icon: 'cloud',
  },
  {
    name: 'Thursday',
    temp: 24,
    description: 'clear sky',
    huminidy: '45%',
    pressure: 1021,
    icon: 'sun',
  },
  {
    name: 'Friday',
    temp: 16,
    description: 'clear sky',
    huminidy: '45%',
    pressure: 1021,
    icon: 'cloud',
  },
  {
    name: 'Saturday',
    temp: 27,
    description: 'clear sky',
    huminidy: '45%',
    pressure: 1021,
    icon: 'sun',
  },
  {
    name: 'Sunday',
    temp: 15,
    description: 'clear sky',
    huminidy: '45%',
    pressure: 1021,
    icon: 'cloud',
  },
];
